project:
  type: website
  resources: 
    - resume.pdf

website:
  title: "Francis Chan"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

excecute:
   freeze: auto

